#!/bin/sh

function sf() {
  ARGS="$@"
  GIT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null)
  CONSOLE=$(git ls-files $GIT_ROOT/app/console 2>/dev/null)

  # Handles symfony/console based application
  if [ -z "$CONSOLE" ]; then
    CONSOLE=$(git ls-files $GIT_ROOT/bin/console 2>/dev/null)
  fi

  if [ -z "$CONSOLE" ]; then
    return 1;
  fi

  docker_compose_wrapper php -d memory_limit=-1 ${CONSOLE} ${ARGS}
}

function phpunit() {
  docker_compose_wrapper php -d memory_limit=-1 bin/phpunit $@
}

function composer() {
  COMPOSER_HOME=${COMPOSER_HOME:-$HOME/.composer} \
  DOCKERFILES_RUN_FLAGS="--memory=2g --tty" \
  docker_compose_wrapper php -d memory_limit=-1 /usr/local/bin/composer $@
}