#!/usr/bin/env sh

# function _update_ps1() {
#    export PS1="$(~/.powerline-shell/powerline-shell.py $?)"
# }

# export PROMPT_COMMAND="_update_ps1"

# Prompt Colors {{{
C_GREEN="\[\033[01;32m\]"
C_BLUE="\[\033[01;34m\]"
C_YELLOW="\[\033[0;33m\]"
C_NONE="\[\033[00m\]"
# }}}


# Prompt Customization
function parse_git_branch {
    test "${HOME}" != "${PWD}" || return
    ref=$(git symbolic-ref HEAD 2> /dev/null) || return
    echo -e "("${ref#refs/heads/}")"
}

export PS1="$C_GREEN\u@\h $C_BLUE\W $C_YELLOW\$(parse_git_branch)$C_BLUE \$ $C_NONE"

# vim:foldmethod=marker:foldlevel=0